plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id 'maven-publish'
    id 'java'
}

def MOD_ID = "showserverlist"
def MOD_NAME = "Show Server List"
def MOD_DESCRIPTION = "???"
def MOD_VERSION = "2.0.0"

def MINECRAFT_VERSION = project.minecraft
def FABRIC_VERSION = project.fabric
def FABRIC_API_VERSION = project.fabric_api

version = MOD_VERSION
group = project.maven_group

base {
    archivesName = MOD_ID
}

loom{
}

repositories {
    google()
    maven {
        url = 'https://maven.parchmentmc.org/'
        content {
            includeGroup 'org.parchmentmc.data'
        }
    }
    maven {
        url = 'https://maven.terraformersmc.com/releases/'
        content {
            includeGroup 'com.terraformersmc'
        }
    }
    maven {
        url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/'
        content {
            includeGroup 'fuzs.forgeconfigapiport'
        }
    }
    maven {
        url = 'https://maven.izzel.io/releases/'
    }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${MINECRAFT_VERSION}"
    implementation "net.fabricmc:fabric-loader:${FABRIC_VERSION}"
    implementation "net.fabricmc.fabric-api:fabric-api:${FABRIC_API_VERSION}"
}

processResources {
    filesMatching("fabric.mod.json") {
        expand "mod_id": MOD_ID,
                "name": MOD_NAME,
                "description": MOD_DESCRIPTION,
                "version": MOD_VERSION,
                "minecraft_version": MINECRAFT_VERSION,
                "loader_version": FABRIC_VERSION
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${MOD_ID}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = MOD_ID
            from components.java
        }
    }
    repositories {
    }
}
